apiVersion: tentacle.joyautomation.com/v1
kind: Gateway
metadata:
  name: gateway
spec:
  devices:
    gateway:
      deadband:
        maxTime: 30000
        minTime: 2500
        value: 1
      protocol: gateway
    mqtt:
      deadband:
        maxTime: 30000
        minTime: 2500
        value: 1
      protocol: mqtt
    network:
      deadband:
        maxTime: 3000
        minTime: 2500
        value: 1
      protocol: network
      scanRate: 2500
    rtu45:
      deadband:
        maxTime: 30000
        minTime: 2500
        value: 1
      host: client4
      protocol: ethernetip
      scanRate: 2500
      templateNameOverrides:
        AB: rtu45_AB
    rtu60:
      deadband:
        maxTime: 30000
        minTime: 2500
        value: 1
      host: client60
      protocol: ethernetip
      scanRate: 2500
      templateNameOverrides:
        AB: rtu60_AB
    test-switch:
      community: public
      deadband:
        maxTime: 2500
        minTime: 2500
        value: 1
      host: 192.168.82.55
      protocol: snmp
      scanRate: 2500
      version: 2c
  udtTemplates:
    Analog_Input:
      name: Analog_Input
      members:
        - name: EnableIn
          datatype: boolean
        - name: EnableOut
          datatype: boolean
        - name: AI
          datatype: number
        - name: SIGNALFAIL
          datatype: boolean
        - name: OVERRANGE
          datatype: boolean
        - name: UNDERRANGE
          datatype: boolean
        - name: SIMULATE
          datatype: boolean
        - name: RAWMIN
          datatype: number
        - name: RAWMAX
          datatype: number
        - name: LOWSCL
          datatype: number
        - name: HIGHSCL
          datatype: number
        - name: SIMVALUE
          datatype: number
        - name: ALMENB
          datatype: boolean
        - name: HHENB
          datatype: boolean
        - name: HHSP
          datatype: number
        - name: HENB
          datatype: boolean
        - name: HSP
          datatype: number
        - name: LENB
          datatype: boolean
        - name: LSP
          datatype: number
        - name: LLENB
          datatype: boolean
        - name: LLSP
          datatype: number
        - name: LOLENB
          datatype: boolean
        - name: LOLSP
          datatype: number
        - name: ALMDLY
          datatype: number
        - name: DB
          datatype: number
        - name: VALUE
          datatype: number
        - name: HH
          datatype: boolean
        - name: H
          datatype: boolean
        - name: L
          datatype: boolean
        - name: LL
          datatype: boolean
        - name: LOS
          datatype: boolean
        - name: OOR
          datatype: boolean
        - name: los_oneshot
          datatype: boolean
        - name: oor_oneshot
          datatype: boolean
      version: "1.0"
    Get_TOD:
      name: Get_TOD
      members:
        - name: EnableIn
          datatype: boolean
        - name: EnableOut
          datatype: boolean
        - name: MONTH
          datatype: number
        - name: DAY
          datatype: number
        - name: YEAR
          datatype: number
        - name: HOUR
          datatype: number
        - name: MINUTE
          datatype: number
        - name: SECOND
          datatype: number
        - name: New_Day
          datatype: boolean
        - name: New_Month
          datatype: boolean
        - name: gettime
          datatype: number
      version: "1.0"
    NetworkInterface:
      name: NetworkInterface
      members:
        - name: operstate
          datatype: string
        - name: carrier
          datatype: boolean
        - name: speed
          datatype: number
        - name: mtu
          datatype: number
        - name: mac
          datatype: string
        - name: rxBytes
          datatype: number
        - name: txBytes
          datatype: number
        - name: rxPackets
          datatype: number
        - name: txPackets
          datatype: number
        - name: rxErrors
          datatype: number
        - name: txErrors
          datatype: number
        - name: rxDropped
          datatype: number
        - name: txDropped
          datatype: number
      version: "1.0"
  udtVariables:
    RTU45_RECLM_PIT_001:
      deviceId: rtu45
      id: RTU45_RECLM_PIT_001
      memberCipTypes:
        AI: REAL
        ALMDLY: INT
        ALMENB: BOOL
        DB: REAL
        EnableIn: BOOL
        EnableOut: BOOL
        H: BOOL
        HENB: BOOL
        HH: BOOL
        HHENB: BOOL
        HHSP: REAL
        HIGHSCL: REAL
        HSP: REAL
        L: BOOL
        LENB: BOOL
        LL: BOOL
        LLENB: BOOL
        LLSP: REAL
        LOLENB: BOOL
        LOLSP: REAL
        LOS: BOOL
        LOWSCL: REAL
        LSP: REAL
        OOR: BOOL
        OVERRANGE: BOOL
        RAWMAX: REAL
        RAWMIN: REAL
        SIGNALFAIL: BOOL
        SIMULATE: BOOL
        SIMVALUE: REAL
        UNDERRANGE: BOOL
        VALUE: REAL
        los_oneshot: BOOL
        oor_oneshot: BOOL
      memberTags:
        AI: RTU45_RECLM_PIT_001.AI
        ALMDLY: RTU45_RECLM_PIT_001.ALMDLY
        ALMENB: RTU45_RECLM_PIT_001.ALMENB
        DB: RTU45_RECLM_PIT_001.DB
        EnableIn: RTU45_RECLM_PIT_001.EnableIn
        EnableOut: RTU45_RECLM_PIT_001.EnableOut
        H: RTU45_RECLM_PIT_001.H
        HENB: RTU45_RECLM_PIT_001.HENB
        HH: RTU45_RECLM_PIT_001.HH
        HHENB: RTU45_RECLM_PIT_001.HHENB
        HHSP: RTU45_RECLM_PIT_001.HHSP
        HIGHSCL: RTU45_RECLM_PIT_001.HIGHSCL
        HSP: RTU45_RECLM_PIT_001.HSP
        L: RTU45_RECLM_PIT_001.L
        LENB: RTU45_RECLM_PIT_001.LENB
        LL: RTU45_RECLM_PIT_001.LL
        LLENB: RTU45_RECLM_PIT_001.LLENB
        LLSP: RTU45_RECLM_PIT_001.LLSP
        LOLENB: RTU45_RECLM_PIT_001.LOLENB
        LOLSP: RTU45_RECLM_PIT_001.LOLSP
        LOS: RTU45_RECLM_PIT_001.LOS
        LOWSCL: RTU45_RECLM_PIT_001.LOWSCL
        LSP: RTU45_RECLM_PIT_001.LSP
        OOR: RTU45_RECLM_PIT_001.OOR
        OVERRANGE: RTU45_RECLM_PIT_001.OVERRANGE
        RAWMAX: RTU45_RECLM_PIT_001.RAWMAX
        RAWMIN: RTU45_RECLM_PIT_001.RAWMIN
        SIGNALFAIL: RTU45_RECLM_PIT_001.SIGNALFAIL
        SIMULATE: RTU45_RECLM_PIT_001.SIMULATE
        SIMVALUE: RTU45_RECLM_PIT_001.SIMVALUE
        UNDERRANGE: RTU45_RECLM_PIT_001.UNDERRANGE
        VALUE: RTU45_RECLM_PIT_001.VALUE
        los_oneshot: RTU45_RECLM_PIT_001.los_oneshot
        oor_oneshot: RTU45_RECLM_PIT_001.oor_oneshot
      tag: RTU45_RECLM_PIT_001
      templateName: Analog_Input
    RTU45_RECLM_PLC_TOD:
      deviceId: rtu45
      id: RTU45_RECLM_PLC_TOD
      memberCipTypes:
        DAY: DINT
        EnableIn: BOOL
        EnableOut: BOOL
        HOUR: DINT
        MINUTE: DINT
        MONTH: DINT
        New_Day: BOOL
        New_Month: BOOL
        SECOND: DINT
        YEAR: DINT
        gettime: DINT
      memberTags:
        DAY: RTU45_RECLM_PLC_TOD.DAY
        EnableIn: RTU45_RECLM_PLC_TOD.EnableIn
        EnableOut: RTU45_RECLM_PLC_TOD.EnableOut
        HOUR: RTU45_RECLM_PLC_TOD.HOUR
        MINUTE: RTU45_RECLM_PLC_TOD.MINUTE
        MONTH: RTU45_RECLM_PLC_TOD.MONTH
        New_Day: RTU45_RECLM_PLC_TOD.New_Day
        New_Month: RTU45_RECLM_PLC_TOD.New_Month
        SECOND: RTU45_RECLM_PLC_TOD.SECOND
        YEAR: RTU45_RECLM_PLC_TOD.YEAR
        gettime: RTU45_RECLM_PLC_TOD.gettime
      tag: RTU45_RECLM_PLC_TOD
      templateName: Get_TOD
    eno1:
      deviceId: network
      id: eno1
      memberTags:
        carrier: eno1_carrier
        mac: eno1_mac
        mtu: eno1_mtu
        operstate: eno1_operstate
        rxBytes: eno1_rxBytes
        rxDropped: eno1_rxDropped
        rxErrors: eno1_rxErrors
        rxPackets: eno1_rxPackets
        speed: eno1_speed
        txBytes: eno1_txBytes
        txDropped: eno1_txDropped
        txErrors: eno1_txErrors
        txPackets: eno1_txPackets
      tag: eno1
      templateName: NetworkInterface
    eno2:
      deviceId: network
      id: eno2
      memberTags:
        carrier: eno2_carrier
        mac: eno2_mac
        mtu: eno2_mtu
        operstate: eno2_operstate
        rxBytes: eno2_rxBytes
        rxDropped: eno2_rxDropped
        rxErrors: eno2_rxErrors
        rxPackets: eno2_rxPackets
        speed: eno2_speed
        txBytes: eno2_txBytes
        txDropped: eno2_txDropped
        txErrors: eno2_txErrors
        txPackets: eno2_txPackets
      tag: eno2
      templateName: NetworkInterface
    eth0:
      deviceId: network
      id: eth0
      memberTags:
        carrier: eth0_carrier
        mac: eth0_mac
        mtu: eth0_mtu
        operstate: eth0_operstate
        rxBytes: eth0_rxBytes
        rxDropped: eth0_rxDropped
        rxErrors: eth0_rxErrors
        rxPackets: eth0_rxPackets
        speed: eth0_speed
        txBytes: eth0_txBytes
        txDropped: eth0_txDropped
        txErrors: eth0_txErrors
        txPackets: eth0_txPackets
      tag: eth0
      templateName: NetworkInterface
    lo:
      deviceId: network
      id: lo
      memberTags:
        carrier: lo_carrier
        mac: lo_mac
        mtu: lo_mtu
        operstate: lo_operstate
        rxBytes: lo_rxBytes
        rxDropped: lo_rxDropped
        rxErrors: lo_rxErrors
        rxPackets: lo_rxPackets
        speed: lo_speed
        txBytes: lo_txBytes
        txDropped: lo_txDropped
        txErrors: lo_txErrors
        txPackets: lo_txPackets
      tag: lo
      templateName: NetworkInterface
    tailscale0:
      deviceId: network
      id: tailscale0
      memberTags:
        carrier: tailscale0_carrier
        mac: tailscale0_mac
        mtu: tailscale0_mtu
        operstate: tailscale0_operstate
        rxBytes: tailscale0_rxBytes
        rxDropped: tailscale0_rxDropped
        rxErrors: tailscale0_rxErrors
        rxPackets: tailscale0_rxPackets
        speed: tailscale0_speed
        txBytes: tailscale0_txBytes
        txDropped: tailscale0_txDropped
        txErrors: tailscale0_txErrors
        txPackets: tailscale0_txPackets
      tag: tailscale0
      templateName: NetworkInterface
  variables:
    gateway/deviceCount:
      datatype: number
      default: 0
      deviceId: gateway
      id: gateway/deviceCount
      tag: deviceCount
    gateway/udtVariableCount:
      datatype: number
      default: 0
      deviceId: gateway
      id: gateway/udtVariableCount
      tag: udtVariableCount
    gateway/uptime:
      datatype: number
      default: 0
      deviceId: gateway
      id: gateway/uptime
      tag: uptime
    gateway/variableCount:
      datatype: number
      default: 0
      deviceId: gateway
      id: gateway/variableCount
      tag: variableCount
    mqtt/connected:
      datatype: boolean
      default: false
      deviceId: mqtt
      id: mqtt/connected
      tag: connected
    mqtt/publishRate:
      datatype: number
      default: 0
      deviceId: mqtt
      id: mqtt/publishRate
      tag: publishRate
    mqtt/storeForward:
      datatype: boolean
      default: false
      deviceId: mqtt
      id: mqtt/storeForward
      tag: storeForward
    mqtt/uptime:
      datatype: number
      default: 0
      deviceId: mqtt
      id: mqtt/uptime
      tag: uptime
    rtu45/RTU45_RECLM_ACP_001_YA:
      cipType: BOOL
      datatype: boolean
      default: false
      deviceId: rtu45
      id: rtu45/RTU45_RECLM_ACP_001_YA
      tag: RTU45_RECLM_ACP_001_YA
    rtu45/RTU45_RECLM_PIT_001_PI:
      cipType: INT
      datatype: number
      deadband:
        value: 10
      default: 0
      deviceId: rtu45
      id: rtu45/RTU45_RECLM_PIT_001_PI
      tag: RTU45_RECLM_PIT_001_PI
    rtu60/RTU60_ZONE13_PIT_001_PI:
      cipType: INT
      datatype: number
      deadband:
        value: 10
      default: 0
      deviceId: rtu60
      id: rtu60/RTU60_ZONE13_PIT_001_PI
      tag: RTU60_ZONE13_PIT_001_PI
    test-switch/dot1dBaseNumPorts.0:
      cipType: Integer32
      datatype: number
      default: 0
      deviceId: test-switch
      id: test-switch/dot1dBaseNumPorts.0
      tag: .1.3.6.1.2.1.17.1.2.0
